#!/bin/sh

default_branch=origin/linux-amd64-default

added_build_dirs=$(git diff --name-only $default_branch... -- builds | awk -F/ '{ print $1"/"$2 }' | uniq)

for directory in $added_build_dirs; do
  lpm --module builder -b ./$directory
done