#!/bin/sh

set -e

default_branch=origin/linux-amd64-default

# Check if the current branch is the default branch
if [ "$(git rev-parse --abbrev-ref HEAD)" = "$(git rev-parse --abbrev-ref $default_branch)" ]; then
  commit_range="HEAD^..HEAD"
else
  commit_range="$default_branch... --"
fi

added_build_dirs=$(git diff --name-only $commit_range -- builds | awk -F/ '{ print $1"/"$2 }' | uniq)

for directory in $added_build_dirs; do
	lpm --module builder -b ./$directory

	echo "\n-------------- RUNNING ci/validate --------------"
	./ci/validate

	if [ "$1" = "PUSH_OUTPUTS" ]; then
		echo "\n-------------- RUNNING ci/push --------------"
		./ci/push
	fi
done
