#!/bin/sh

set -e

git clone https://github.com/lodosgroup/lpm-modules -b stable
cd lpm-modules/lpm-builder
make build

sudo lpm --yes --module --add builder ./build/liblpm_builder.so
lpm --module --list
