#!/bin/sh

set -e

pkg=$(find *.lod -type f)
index_patch=$(find *.sql -type f)

# push pkg
backblaze-b2 authorize-account $B2_ACCOUNT_ID $B2_APPLICATION_KEY
backblaze-b2 upload-file linux-amd64-default $pkg packages/$pkg

# TODO(push index)
# clone repository index if not exists;
# cd to repo and checkout to linux-amd64-default branch
# create $pkg branch and push the index file

rm $pkg
rm $index_patch
