#!/bin/sh

pkg=$(find *.lod -type f)
index_patch=$(find *.sql -type f)

echo "validating $index_patch"
sqlite3 ./ci/repository.db < $index_patch

echo "validating $pkg"
sudo lpm --install $pkg --local