name: build
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install lpm
        run: |
          cargo install lpm --git https://github.com/foss-lodpm/lpm.git --branch stable
          sudo ln -s ~/.cargo/bin/lpm /usr/bin/lpm # a simple workaround for "sudo: lpm command not found" problem

      - name: lpm --configure
        run: |
          sudo lpm --configure

      - name: ci/pre-build
        run: ./ci/pre-build

      - name: ci/build
        run: ./ci/build
